#!/bin/bash
#

ANS_ARGS=""

usage() {
    echo $"Usage: $0 {play|check} {playbook-file}"
	echo ""
	echo $"This always run on localhost"
    exit 1
}

_set_verbose() {
	ANS_ARGS="$ANS_ARGS -vv"
}

ansible_play() {
	local PLAYBOOK_PATH=$1
	local ANS_EXEC="ansible-playbook"
	
	ANS_ARGS="$ANS_ARGS --connection=local --ask-sudo-pass"

	_set_verbose
	ANS_ARGS="${PLAYBOOK_PATH} $ANS_ARGS"

	echo "Exec... '${ANS_EXEC} ${ANS_ARGS}'"
	${ANS_EXEC} ${ANS_ARGS}
}

ansible_test() {
	local PLAYBOOK_PATH=$1
	local ANS_EXEC="ansible-playbook"
	
	ANS_ARGS="$ANS_ARGS -e is_testing=true --connection=local --sudo"

	_set_verbose
	ANS_ARGS="${PLAYBOOK_PATH} $ANS_ARGS"

	echo "Exec... '${ANS_EXEC} ${ANS_ARGS}'"
	${ANS_EXEC} ${ANS_ARGS}
}

ansible_check() {
	local PLAYBOOK_PATH=$1
	local ANS_EXEC="ansible-playbook"

	ANS_ARGS="$ANS_ARGS --connection=local --ask-sudo-pass"

	ANS_ARGS="$ANS_ARGS --syntax-check "
	
	_set_verbose
	
	ANS_ARGS="${PLAYBOOK_PATH} $ANS_ARGS"

	echo "Exec... '${ANS_EXEC} ${ANS_ARGS}'"
	${ANS_EXEC} ${ANS_ARGS}
}


case "$1" in
	play)
	    ansible_play $2 $3
		;;
	test)
	    ansible_test $2 $3
		;;
	check)
	    ansible_check $2 $3
	    ;;
	*)  
	    usage
	    ;;
esac

